// Generated by Haxe 4.3.6
(function ($hx_exports, $global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var CursorConverter = function() { };
CursorConverter.__name__ = true;
CursorConverter.run = function(d,width,height,cx,cy) {
	var o = new haxe_io_BytesOutput();
	var area = width * height;
	var size = area * 4 + Math.ceil(area / 8);
	var b_arr = new Array(size + 62);
	var b_pos = 0;
	var b_val = 0;
	var bw = width;
	if(bw > 255) {
		bw = 0;
	}
	var bh = height;
	if(bh > 255) {
		bh = 0;
	}
	b_val = 0;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_val = 2;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_val = 1;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = bw;
	b_arr[b_pos++] = bh;
	b_arr[b_pos++] = 0;
	b_arr[b_pos++] = 0;
	b_val = cx;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_val = cy;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_val = size + 40;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = b_pos + 4;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = 40;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = width;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = height * 2;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = 1;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_val = 32;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_val = 0;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = 0;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = 0;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = 0;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = 0;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	b_val = 0;
	b_arr[b_pos++] = b_val & 255;
	b_arr[b_pos++] = b_val >> 8 & 255;
	b_arr[b_pos++] = b_val >> 16 & 255;
	b_arr[b_pos++] = b_val >>> 24 & 255;
	var maskPos = b_pos + area * 4;
	var maskBit = 0;
	var dy = height;
	while(--dy >= 0) {
		var _g = 0;
		var _g1 = width;
		while(_g < _g1) {
			var dx = _g++;
			var dp = dy * width + dx << 2;
			var dr = d[dp];
			var dg = d[dp + 1];
			var db = d[dp + 2];
			var da = d[dp + 3];
			b_arr[b_pos++] = db;
			b_arr[b_pos++] = dg;
			b_arr[b_pos++] = dr;
			b_arr[b_pos++] = da;
			var dm = da == 0 ? 1 << 7 - maskBit : 0;
			b_arr[maskPos] |= dm;
			if(++maskBit == 8) {
				maskBit = 0;
				++maskPos;
			}
		}
	}
	var b64 = window;
	var this1 = b_arr;
	var f = _$String_String_$Impl_$.fromCharCode;
	var length = this1.length;
	var r = new Array(length);
	var len = length;
	var _g = 0;
	var _g1 = len;
	while(_g < _g1) {
		var i = _g++;
		var v = f(this1[i]);
		r[i] = v;
	}
	var this1 = r;
	var b_b = "";
	var len = this1.length;
	var _g = 0;
	var _g1 = len;
	while(_g < _g1) {
		var i = _g++;
		b_b += Std.string(Std.string(this1[i]));
		if(i < len - 1) {
			b_b += "";
		}
	}
	var b641 = b64.btoa(b_b);
	return "data:image/x-icon;base64," + b641;
};
// ID-based cursor storage: GX Games strips JS object prototypes when
// passing through GML variables. Store cursors by numeric ID so GML
// only handles numbers, not raw JS objects.
var _nc_cursors = {};
var _nc_nextId = 1;
function _nc_store(cursor) { var id = _nc_nextId++; _nc_cursors[id] = cursor; return id; }
function _nc_get(id) { return _nc_cursors[id] || null; }
function _nc_remove(id) { delete _nc_cursors[id]; }
var Extension = function() { };
Extension.__name__ = true;
///~
Extension.createEmpty = $hx_exports["native_cursor_create_empty"] = function() {
	return _nc_store(new NativeCursor());
};
///~
Extension.createFromBuffer = $hx_exports["native_cursor_create_from_buffer"] = function(buf,width,height,x,y,fps) {
	var cur = new NativeCursor();
	cur.addFromBuffer(buf,width,height,x,y);
	return _nc_store(cur);
};
///~
Extension.addFromBuffer = $hx_exports["native_cursor_add_from_buffer"] = function(id,buf,width,height,x,y) {
	var cur = _nc_get(id);
	if (cur) cur.addFromBuffer(buf,width,height,x,y);
	return id;
};
///~
Extension.destroy = $hx_exports["native_cursor_destroy"] = function(id) {
	var cur = _nc_get(id);
	if (cur) {
		if(cur == NativeCursor.current) { NativeCursorFrame.reset(); }
		cur.destroy();
		_nc_remove(id);
	}
};
///~
Extension.update = $hx_exports["native_cursor_update"] = function() {
	var cur = NativeCursor.current;
	if(cur != null && cur.frames.length > 0) {
		cur.apply(false);
	}
	return false;
};
///~
Extension.set = $hx_exports["native_cursor_set"] = function(id) {
	var cur = _nc_get(id);
	if (!cur) return;
	var current = NativeCursor.current;
	if(current != null) {
		current.timeOffset = new Date().getTime() - current.timeStart;
	}
	NativeCursor.current = cur;
	cur.timeStart = new Date().getTime() - cur.timeOffset;
	cur.apply(false);
	if (!NativeCursor._timer) {
		NativeCursor._timer = setInterval(function() {
			var c = NativeCursor.current;
			if (c && c.frames.length > 0) c.apply(true);
		}, 16);
	}
};
///~
Extension.reset = $hx_exports["native_cursor_reset"] = function() {
	var current = NativeCursor.current;
	if(current != null) {
		current.timeOffset = new Date().getTime() - current.timeStart;
	}
	NativeCursor.current = null;
	NativeCursor.currentFrame = null;
	NativeCursorFrame.reset();
	if (NativeCursorFrame.canvas) NativeCursorFrame.canvas.style.cursor = "none";
	if (NativeCursor._timer) {
		clearInterval(NativeCursor._timer);
		NativeCursor._timer = null;
	}
};
///~
Extension.getFrame = $hx_exports["native_cursor_get_frame"] = function(id) {
	var cur = _nc_get(id);
	return cur ? cur.getCurrentFrame() : -1;
};
///~
Extension.setFrame = $hx_exports["native_cursor_set_frame"] = function(id,frame) {
	var cur = _nc_get(id);
	if (cur) cur.setFrame(frame);
};
///~
Extension.getFramerate = $hx_exports["native_cursor_get_framerate"] = function(id) {
	var cur = _nc_get(id);
	return cur ? cur.framerate : 0;
};
///~
Extension.setFramerate = $hx_exports["native_cursor_set_framerate"] = function(id,fps) {
	var cur = _nc_get(id);
	if (cur) { cur.framerate = fps; cur.timeMult = fps / 1000.0; }
};
///~
Extension.init = $hx_exports["native_cursor_preinit_raw"] = function(canvasID,_) {
	var canvas = window.document.getElementById(canvasID);
	canvas.addEventListener("mousemove",function(e) {
		return NativeCursor.moved = true;
	});
	NativeCursorFrame.canvas = canvas;
	NativeCursorFrame.init();
	return true;
};
Extension.main = function() {
};
Math.__name__ = true;
var NativeCursor = function() {
	this.framerate = 30.0;
	this.timeMult = 30.0;
	this.timeOffset = 0.0;
	this.timeStart = 0.0;
	this.frames = [];
	this.timeStart = new Date().getTime();
};
NativeCursor.__name__ = true;
NativeCursor.getTime = function() {
	return new Date().getTime();
};
NativeCursor.prototype = {
	get_count: function() {
		return this.frames.length;
	}
	,destroy: function() {
		var _g = 0;
		var _g1 = this.frames;
		while(_g < _g1.length) {
			var frame = _g1[_g];
			++_g;
			frame.destroy();
		}
		this.frames.length = 0;
	}
	,addFromBuffer: function(buf,width,height,x,y) {
		var arr;
		if (typeof buf === "string") {
			var binary = atob(buf.replace(/[\s=]+$/g, '').replace(/\s/g, ''));
			arr = new Uint8ClampedArray(binary.length);
			for (var i = 0; i < binary.length; i++) arr[i] = binary.charCodeAt(i);
		} else if (typeof window.gml_Script_gmcallback__native_cursor__buffer_get_address === "function") {
			arr = new Uint8ClampedArray(window.gml_Script_gmcallback__native_cursor__buffer_get_address(null,null,buf));
		}
		if (!arr) return;
		var url = CursorConverter.run(arr,width,height,x,y);
		var frame = new NativeCursorFrame(url);
		this.frames.push(frame);
	}
	,getCurrentFrame: function() {
		var n = this.frames.length;
		if(n <= 0) {
			return -1;
		}
		var t = new Date().getTime() - this.timeStart;
		var f = t * this.timeMult;
		var fi = (f | 0) % n;
		if(fi < 0) {
			fi += n;
		}
		return fi;
	}
	,setFrame: function(frame) {
		var n = this.frames.length;
		if(n <= 0) {
			return false;
		}
		frame %= n;
		if(frame < 0) {
			frame += n;
		}
		if(this == NativeCursor.current) {
			this.timeStart = new Date().getTime() - (frame / this.timeMult | 0);
		} else {
			this.timeOffset = frame / this.timeMult | 0;
		}
		return true;
	}
	,apply: function(force) {
		var cur = NativeCursor.current;
		if(cur == null || cur.frames.length == 0) {
			return false;
		}
		var frame = cur.frames[cur.getCurrentFrame()];
		if(frame == null) {
			return false;
		}
		if(!force && frame == NativeCursor.currentFrame) {
			return true;
		}
		NativeCursor.currentFrame = frame;
		frame.apply();
		return true;
	}
};
var NativeCursorFrame = function(dataURL) {
	this.id = Std.string(NativeCursorFrame.nextID++);
	this.selector = "canvas[" + "data-cursor" + "=\"" + this.id + "\"]";
	var rule = "" + this.selector + " { cursor: url(" + dataURL + "), default; }";
	NativeCursorFrame.styleSheet.insertRule(rule,NativeCursorFrame.styleSheet.cssRules.length);
	NativeCursorFrame.style.dataset.count = "" + ++NativeCursorFrame.count;
};
NativeCursorFrame.__name__ = true;
NativeCursorFrame.reset = function() {
	NativeCursorFrame.canvas.removeAttribute("data-cursor");
	var pc = NativeCursorFrame.prevCursor;
	if(pc != null) {
		NativeCursorFrame.canvas.style.cursor = pc;
		NativeCursorFrame.prevCursor = null;
	}
};
NativeCursorFrame.init = function() {
	NativeCursorFrame.style = window.document.createElement("style");
	NativeCursorFrame.style.id = "native_cursor";
	window.document.body.appendChild(NativeCursorFrame.style);
	NativeCursorFrame.styleSheet = NativeCursorFrame.style.sheet;
};
NativeCursorFrame.prototype = {
	destroy: function() {
		var rules = NativeCursorFrame.styleSheet.cssRules;
		var _g = 0;
		var _g1 = rules.length;
		while(_g < _g1) {
			var i = _g++;
			var rule = rules[i];
			var tmp = rule.selectorText;
			var sel = tmp != null ? tmp : rule.cssText;
			if(StringTools.startsWith(sel,this.selector)) {
				NativeCursorFrame.styleSheet.deleteRule(i);
				break;
			}
		}
		NativeCursorFrame.style.dataset.count = "" + --NativeCursorFrame.count;
	}
	,apply: function() {
		NativeCursorFrame.canvas.setAttribute("data-cursor",this.id);
		var cur = NativeCursorFrame.canvas.style.cursor;
		if(cur != "") {
			NativeCursorFrame.prevCursor = cur;
			NativeCursorFrame.canvas.style.cursor = "";
		}
	}
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var _$String_String_$Impl_$ = function() { };
_$String_String_$Impl_$.__name__ = true;
_$String_String_$Impl_$.fromCharCode = function(code) {
	return String.fromCodePoint(code);
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.startsWith = function(s,start) {
	if(s.length >= start.length) {
		return s.lastIndexOf(start,0) == 0;
	} else {
		return false;
	}
};
var haxe_io_BytesBuffer = function() {
	this.pos = 0;
	this.size = 0;
};
haxe_io_BytesBuffer.__name__ = true;
var haxe_io_Output = function() { };
haxe_io_Output.__name__ = true;
var haxe_io_BytesOutput = function() {
	this.b = new haxe_io_BytesBuffer();
};
haxe_io_BytesOutput.__name__ = true;
haxe_io_BytesOutput.__super__ = haxe_io_Output;
haxe_io_BytesOutput.prototype = $extend(haxe_io_Output.prototype,{
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
if( String.fromCodePoint == null ) String.fromCodePoint = function(c) { return c < 0x10000 ? String.fromCharCode(c) : String.fromCharCode((c>>10)+0xD7C0)+String.fromCharCode((c&0x3FF)+0xDC00); }
String.__name__ = true;
Array.__name__ = true;
Date.__name__ = "Date";
js_Boot.__toStr = ({ }).toString;
NativeCursor.current = null;
NativeCursor.moved = false;
NativeCursorFrame.nextID = 0;
NativeCursorFrame.count = 0;
Extension.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, {});
